docs/commands.md, resources/assets/js/components/list/EntityList.vue, saturn/app/Sharp/Commands/SpaceshipExternalLink.php, saturn/app/Sharp/SpaceshipSharpList.php, src/EntityList/Commands/Command.php, tests/Feature/Api/CommandControllerTest.php
Hi,
I required a command which allows the front end to redirect to a link specified for the instance
=> A Command may return a link for the application to follow

src/Http/Composers/MenuViewComposer.php
Hello,
This PR fixes issue #40.
=> Initialize $entities as an empty array in MenuCategory

src/Form/Fields/Formatters/MarkdownFormatter.php, src/Form/Fields/Formatters/UploadFormatter.php, tests/Unit/Form/Fields/Formatters/MarkdownFormatterTest.php
=> Fix formatters and test

docs/dashboard-widgets/graph.md
Correction of method call in the example.
=> Fix correct function call

resources/assets/js/__tests__/EntityList.test.js, resources/assets/js/__tests__/__snapshots__/ActionBar.test.js.snap, resources/assets/js/__tests__/__snapshots__/EntityList.test.js.snap, resources/assets/js/__tests__/__snapshots__/FilterSelect.test.js.snap, resources/assets/js/__tests__/__snapshots__/LeftNav.test.js.snap, resources/assets/js/components/action-bar/ActionBar.vue, resources/assets/js/components/action-bar/ActionBarList.vue, resources/assets/js/components/dropdown/Dropdown.vue, resources/assets/js/components/list/EntityList.vue, resources/assets/js/components/list/FilterSelect.vue, resources/assets/js/components/list/StateIcon.vue, resources/assets/js/components/menu/LeftNav.vue, resources/assets/sass/_vars.scss, resources/assets/sass/app.scss, resources/assets/sass/components/_ActionBar.scss, resources/assets/sass/components/_Dropdown.scss, resources/assets/sass/components/_LeftNav.scss, resources/assets/sass/components/form/_Form.scss, resources/assets/sass/components/form/_Multiselect.scss, resources/assets/sass/components/list/_EntityList.scss, resources/assets/sass/components/list/_FilterSelect.scss, resources/assets/sass/mixins/_modifiers.scss, resources/views/partials/_menu.blade.php
=> Improve list page UI

resources/assets/js/components/DynamicViewMixin.js, resources/assets/js/components/form/Form.vue, resources/assets/js/components/list/EntityList.vue, resources/assets/js/consts.js, resources/assets/js/util.js, resources/views/layout.blade.php, saturn/config/sharp.php, src/routes.php, src/sharp_helper.php, tests/Feature/CustomUrlSegmentTest.php
=> Configurable base url

saturn/config/sharp.php, src/sharp_helper.php
=> Enhance sharp_page_title() helper to handle multiforms and allow to hide sharp version

resources/assets/js/components/list/StateIcon.vue, resources/assets/sass/app.scss, resources/assets/sass/components/list/_StateIcon.scss
=> State icon as component, fix color classes

docs/commands.md, saturn/app/Sharp/Commands/PilotDownloadPhoto.php, saturn/app/Sharp/Commands/TravelsDashboardDownloadCommand.php, saturn/app/Sharp/TravelsDashboard.php, src/Dashboard/Commands/DashboardCommand.php, src/Dashboard/SharpDashboard.php, src/EntityList/Traits/HandleCommands.php, src/EntityList/Traits/HandleDashboardCommands.php, src/Http/Api/Commands/DashboardCommandController.php, src/Http/Api/Commands/HandleCommandReturn.php, src/routes.php, src/sharp_helper.php, tests/Feature/Api/CommandControllerTest.php, tests/Unit/Dashboard/DashboardCommandTest.php
Allow commands in dashboard pages.
Cf. [commands](https://github.com/code16/sharp/blob/master/docs/commands.md#commands-for-dashboard) docs
=> Commands in dashboard

.gitignore, .travis.yml, composer.json, src/Http/Middleware/Api/SaveEntityListParams.php, tests/Feature/Api/BaseApiTest.php, tests/Feature/Api/CommandControllerTest.php, tests/Feature/Api/ContextTest.php, tests/Feature/Api/DashboardControllerTest.php, tests/Feature/Api/DataLocalizationTest.php, tests/Feature/Api/EntityListControllerTest.php, tests/Feature/Api/FiltersInRequestTest.php, tests/Feature/Api/FormControllerTest.php, tests/Feature/Api/FormDownloadControllerTest.php, tests/Feature/Api/FormUploadControllerTest.php, tests/Feature/Api/GlobalFiltersTest.php, tests/Feature/Api/MultiFormEntityFormControllerTest.php, tests/Feature/Api/MultiFormEntityListControllerTest.php, tests/Feature/Api/PolicyAuthorizationsTest.php, tests/Feature/Api/SetLocaleTest.php, tests/Feature/Api/SharpValidatorTest.php, tests/Feature/MenuViewComposerTest.php, tests/SharpTestCase.php, tests/Unit/Form/Fields/Formatters/MarkdownFormatterTest.php, tests/Unit/Form/Fields/Formatters/UploadFormatterTest.php, tests/Unit/Form/Fields/SharpFormAutocompleteFieldTest.php, tests/Unit/Form/Validator/SharpValidatorTest.php, tests/Unit/Utils/FileUtilTest.php
=> Laravel 5.8 support

resources/lang/back/es/auth.php, resources/lang/back/es/errors.php, resources/lang/back/es/login.php, resources/lang/back/es/menu.php, resources/lang/front/es/action_bar.php, resources/lang/front/es/dashboard.php, resources/lang/front/es/entity_list.php, resources/lang/front/es/form.php, resources/lang/front/es/modals.php
I translated all the texts into Spanish, since I could not overwrite them in the way that laravel provides. I hope it helps.
=> Spanish translations

config/config.php, src/SharpServiceProvider.php
=> Add default config file.

docs/guide/dashboard-widgets/ordered-list.md
I noticed the strings in the example code were not terminated.
=> Fix example code

resources/lang/front/en/entity_list.php
=> Translate filter.search_placeholder to English

docs/guide/dashboard-widgets/ordered-list.md, docs/guide/dashboard.md, docs/guide/link-to-entity.md, saturn/app/Sharp/CompanyDashboard.php, src/Dashboard/SharpDashboard.php, src/Dashboard/Widgets/SharpOrderedListWidget.php, src/Dashboard/Widgets/SharpWidget.php, src/Utils/LinkToEntity.php, tests/Unit/Dashboard/SharpDashboardTest.php
Add a Sharp way to build ORderListWidget item urls. 
Meant to replace #178.
=> enhance ordered list widget link building

resources/lang/back/ko-kr/auth.php, resources/lang/back/ko-kr/errors.php, resources/lang/back/ko-kr/login.php, resources/lang/back/ko-kr/menu.php, resources/lang/front/ko-kr/action_bar.php, resources/lang/front/ko-kr/dashboard.php, resources/lang/front/ko-kr/entity_list.php, resources/lang/front/ko-kr/form.php, resources/lang/front/ko-kr/modals.php
I need Korean Translation and soon also gonna make Portuguese Translation for upcoming projects.
=> Korean initial translation

src/SharpServiceProvider.php
Updated to match changes in intervention/image 2.5.1
=> Updated for compatability with intervention/image 2.5.1

resources/assets/js/__tests__/pages/ShowPage.test.js, resources/assets/js/__tests__/pages/__snapshots__/ShowPage.test.js.snap, resources/assets/js/components/dev/UnknownField.vue, resources/assets/js/components/form/field-display/FieldDisplay.js, resources/assets/js/components/pages/ShowPage.vue
=> Display error on the page if unknown field is defined in layout

resources/lang/back/nl/auth.php, resources/lang/back/nl/errors.php, resources/lang/back/nl/login.php, resources/lang/back/nl/menu.php, resources/lang/front/nl/action_bar.php, resources/lang/front/nl/dashboard.php, resources/lang/front/nl/entity_list.php, resources/lang/front/nl/form.php, resources/lang/front/nl/modals.php, resources/lang/front/nl/show.php
I've added Dutch translations for Sharp.
If there is anything I missed (or translated weirdly), please let me know and I will update the translation(s). :smile:
=> Added Dutch translations

resources/lang/back/nl/auth.php, resources/lang/front/nl/entity_list.php, resources/lang/front/nl/form.php
As mentioned in #212 by @WaveHack, I made some minor grammar mistakes and typos in my initial translation. This fixes them :)
=> Fixed some minor Dutch translations

resources/lang/front/ru/action_bar.php, resources/lang/front/ru/dashboard.php, resources/lang/front/ru/entity_list.php, resources/lang/front/ru/form.php, resources/lang/front/ru/show.php
=> fix front translation

resources/assets/js/components/list/EntityList.vue, resources/assets/js/components/pages/DashboardPage.vue, resources/assets/js/store/modules/__mocks__/filters.js
=> Fix: retained filter values are not set on Commands

docs/guide/entity-states.md
as the title states a minor correction, i stumbled on
=> Documentation fix for entity-state artisan command

src/SharpServiceProvider.php
=> #222 Add sharp::show to AssetComposer definition

saturn/app/Sharp/CustomFormFields/SharpCustomFormFieldTextIcon.php, saturn/app/Sharp/PilotJuniorSharpForm.php
Hello sharp,
i'm sorry for this so small patch / PR but there is a typo in saturn example ... so this is my (no)contribution to sharp :-)
=> There is a very small typo in saturn example: Fom -> Form (r is missing)

packages/show/__tests__/ShowPage.test.js, packages/show/src/components/pages/ShowPage.vue, saturn/app/Sharp/PilotSharpShow.php, src/Http/Middleware/Api/AppendMultiformInEntityList.php, src/SharpServiceProvider.php, src/Show/SharpShow.php, src/routes.php, tests/Unit/Show/SharpShowTest.php
=> Multiforms in show

docs/guide/form-fields/markdown.md, docs/guide/upgrading/6.0.md, packages/form/__tests__/fields/Markdown.test.js, packages/form/__tests__/fields/__snapshots__/Markdown.test.js.snap, packages/form/scss/components/fields/_Markdown.scss, packages/form/scss/components/fields/_TrixEditor.scss, packages/form/scss/components/fields/_editor.scss, packages/form/scss/form.scss, packages/form/src/components/fields/markdown/Markdown.vue, packages/form/src/components/fields/markdown/MarkdownUpload.vue, packages/form/src/components/fields/markdown/config.js, packages/form/src/components/fields/upload/VueClip.vue, packages/form/src/util/icons.js, resources/views/partials/markdown-embedded-file.blade.php, resources/views/public/markdown-embedded-file.blade.php, saturn/app/Sharp/SpaceshipSharpForm.php, saturn/app/Sharp/SpaceshipSharpShow.php, saturn/app/Sharp/TestForm/TestForm.php, saturn/resources/views/sharp/spaceship-preview.blade.php, saturn/resources/views/vendor/sharp/public/markdown-embedded-file.blade.php, src/Form/Fields/Formatters/MarkdownFormatter.php, src/Form/Fields/SharpFormMarkdownField.php, src/Form/Fields/SharpFormUploadField.php, src/Form/Fields/Utils/SharpFormFieldWithUpload.php, src/SharpServiceProvider.php, src/Utils/Transformers/Attributes/MarkdownAttributeTransformer.php, src/sharp_helper.php, tests/Unit/Form/Fields/Formatters/MarkdownFormatterTest.php, tests/Unit/Form/Fields/SharpFormMarkdownFieldTest.php, tests/Unit/Utils/Transformers/MarkdownAttributeTransformerTest.php
=> Handle non image markdown upload

packages/form/src/components/fields/markdown/Markdown.vue, packages/form/src/components/fields/markdown/tables.js
=> Handle pasting table in markdown field

packages/commands/src/components/CommandFormModal.vue, packages/form/src/components/Form.vue, packages/ui/__tests__/Modal.test.js, packages/ui/scss/components/_Modal.scss, packages/ui/scss/components/loading/_Loading.scss, packages/ui/scss/mixins/_button.scss, packages/ui/src/components/Loading.vue, packages/ui/src/components/Modal.vue
=> Add loading indicator in command form

docs/guide/building-entity-form.md, packages/entity-list/__tests__/EntityList.test.js, packages/filters/src/components/GlobalFilters.vue, packages/form/__tests__/Form.test.js, packages/form/src/components/Form.vue, packages/test-utils/src/setup/mockument.js, resources/assets/js/__tests__/util/url.test.js, resources/assets/js/util/breadcrumb.js, saturn/app/Sharp/CustomFormFields/SharpCustomFormFieldTextIcon.php, saturn/app/Sharp/PilotJuniorSharpForm.php, saturn/app/Sharp/PilotSeniorSharpForm.php, saturn/app/Sharp/SpaceshipSharpForm.php, src/Form/SharpForm.php, src/Form/SharpSingleForm.php, src/Http/Api/ApiController.php, src/Http/Api/FormController.php, src/Http/Context/CurrentSharpRequest.php, tests/Feature/Api/FormControllerTest.php, tests/Feature/Api/MultiFormEntityFormControllerTest.php, tests/Unit/Form/SharpFormTest.php, tests/Unit/Utils/CurrentSharpRequestTest.php, tests/Unit/Utils/WithCurrentSharpRequestFake.php
=> Redirect to sp after store

packages/entity-list/__tests__/EntityList.test.js, packages/entity-list/src/components/ActionBar.vue, packages/entity-list/src/components/EntityList.vue, packages/entity-list/src/components/pages/EntityListPage.vue, packages/show/src/components/fields/entity-list/ActionBar.vue, packages/ui/scss/components/_Search.scss, packages/ui/src/components/Search.vue, resources/assets/sass/_bootstrap.scss, resources/assets/sass/_variables.scss
- search button
- clear reloads the page
=> Improve search styling

packages/form/src/components/fields/list/List.vue, packages/form/src/util/transform-fields.js
closes https://github.com/code16/sharp/issues/341
=> Fix list item id attribute

resources/lang/back/en/menu.php, resources/lang/back/fr/menu.php, resources/views/components/menu.blade.php, src/routes.php
=> Change logout endpoint to POST

docs/guide/filters.md
replaced with ```$this->queryParams```
=> Sharp 7 has no $params any more

docs/guide/upgrading/7.0.md
I was doing the upgrade to 7.0 and noticed this little error (probably caused by copy-paste)
=> Fix upgrade documentation

src/Console/stubs/entity-list.model.stub, src/Console/stubs/form.model.stub, src/Console/stubs/show-page.model.stub, src/Console/stubs/show-page.stub
Some minor changes when using the command line.
Making some functions public, initial values like the return type, `;` at the end.
=> Fixing some Artisan generators
